# Generated by Django 6.0.3 on 2026-03-24 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_status_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='address',
        ),
        migrations.RemoveField(
            model_name='application',
            name='comm_address',
        ),
        migrations.RemoveField(
            model_name='application',
            name='district',
        ),
        migrations.RemoveField(
            model_name='application',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='application',
            name='email',
        ),
        migrations.RemoveField(
            model_name='application',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='application',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='application',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='application',
            name='state',
        ),
    ]
