# Generated by Django 6.0.3 on 2026-03-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_application_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='caste',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='quota',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
