# Generated by Django 6.0.3 on 2026-03-24 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_formfield_is_name_field_and_more'),
        ('applications', '0004_application_caste_application_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='caste',
        ),
        migrations.RemoveField(
            model_name='application',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='application',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='application',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='application',
            name='quota',
        ),
        migrations.CreateModel(
            name='ApplicationFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='applications.application')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.formfield')),
            ],
        ),
    ]
