# Generated by Django 6.0.3 on 2026-03-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_remove_application_caste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('hold', 'On Hold')], default='pending', max_length=20),
        ),
    ]
