# Generated by Django 6.0.3 on 2026-03-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('hold', 'On Hold')], default='pending', max_length=20),
        ),
    ]
