# Generated by Django 6.0.3 on 2026-04-02 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_course_course_category_labels_and_more'),
        ('applications', '0008_alter_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category_type', models.CharField(choices=[('semester', 'Semester'), ('year', 'Year')], max_length=10)),
                ('breakdown', models.JSONField(default=list, help_text='List of fee amounts per period')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_categories', to='academics.course')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(max_length=50, unique=True)),
                ('date_of_join', models.DateField()),
                ('calculated_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_reason', models.TextField(blank=True, null=True)),
                ('final_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('care_of', models.CharField(blank=True, max_length=255, null=True)),
                ('guardian_name', models.CharField(max_length=255)),
                ('guardian_mobile', models.CharField(max_length=20)),
                ('relationship', models.CharField(max_length=100)),
                ('guardian_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='applications.application')),
                ('selected_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.course')),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.feecategory')),
            ],
        ),
    ]
