# Generated by Django 6.0.3 on 2026-04-02 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_formfield_category_type_and_more'),
        ('applications', '0009_feecategory_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecategory',
            name='course_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_categories', to='academics.coursecategory'),
        ),
        migrations.AlterField(
            model_name='feecategory',
            name='category_type',
            field=models.CharField(blank=True, choices=[('semester', 'Semester'), ('year', 'Year')], max_length=10, null=True),
        ),
    ]
