# Generated by Django 6.0.3 on 2026-04-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_feecategory_course_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feecategory',
            name='course_category',
        ),
        migrations.AlterField(
            model_name='feecategory',
            name='category_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
