# Generated by Django 6.0.3 on 2026-04-02 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_remove_coursecategory_institute_and_more'),
        ('applications', '0011_remove_feecategory_course_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='joining_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='academics.coursesubcategory'),
        ),
    ]
