# Generated by Django 5.2.9 on 2026-04-02 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_admission_joining_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='annual_serial',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='admission',
            name='register_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('warned', 'Warned'), ('suspended', 'Suspended'), ('trashed', 'Trashed')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='admission',
            name='status_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='registration_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='FeeSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='applications.feecategory')),
            ],
        ),
    ]
