# Generated by Django 5.2.9 on 2026-04-11 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_admission_annual_serial_admission_register_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. CCAvenue Production, PhiCommerce UAT', max_length=100)),
                ('gateway_type', models.CharField(choices=[('ccavenue', 'CCAvenue'), ('phicommerce', 'PhiCommerce')], max_length=20)),
                ('merchant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('access_code', models.CharField(blank=True, max_length=255, null=True)),
                ('working_key', models.CharField(blank=True, max_length=255, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('terminal_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.paymentconfig'),
        ),
    ]
