# Generated by Django 5.2.9 on 2026-04-13 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_class_subject'),
        ('applications', '0014_paymentconfig_payment_gateway_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='assigned_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='academics.class'),
        ),
    ]
