# Generated by Django 5.2.9 on 2026-04-15 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_applicationform_academic_year_and_more'),
        ('applications', '0015_admission_assigned_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationfieldvalue',
            name='field_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationfieldvalue',
            name='field_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='applicationfieldvalue',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.formfield'),
        ),
    ]
