# Generated by Django 6.0.3 on 2026-04-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_applicationfieldvalue_field_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='merchant_txn_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('CARD', 'Card'), ('NB', 'NetBanking'), ('UPI', 'UPI')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='tran_ctx',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='base_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='callback_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='environment',
            field=models.CharField(choices=[('uat', 'UAT'), ('prod', 'Production')], default='uat', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentconfig',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
