# Generated by Django 5.2.3 on 2026-04-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_payment_merchant_txn_no_payment_payment_mode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
    ]
