# Generated by Django 5.2.3 on 2026-05-02 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_applicationfeetype'),
        ('applications', '0018_alter_admission_options_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='selected_fee_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.applicationfeetype'),
        ),
    ]
