# Generated by Django 5.2.3 on 2026-05-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_application_selected_fee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconfig',
            name='aggregator_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
