# Generated by Django 5.2.3 on 2026-05-25 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_feecategorymaster_feetype_classyear_feestructure_and_more'),
        ('applications', '0020_paymentconfig_aggregator_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='assigned_class_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='academics.classyear'),
        ),
        migrations.AddField(
            model_name='admission',
            name='assigned_fee_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='academics.feecategorymaster'),
        ),
        migrations.AddField(
            model_name='admission',
            name='custom_discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overrides fee category discount head percentage if set', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='fee_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.feecategory'),
        ),
        migrations.AlterField(
            model_name='paymentconfig',
            name='aggregator_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentconfig',
            name='merchant_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
