# Generated by Django 5.2.3 on 2026-07-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_admission_assigned_class_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('CARD', 'Card'), ('NB', 'NetBanking'), ('UPI', 'UPI'), ('CASH', 'Cash')], max_length=10, null=True),
        ),
    ]
