# Generated by Django 5.2.3 on 2026-07-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_alter_payment_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(blank=True, help_text='For manual payments', null=True),
        ),
    ]
