# Generated by Django 5.2.3 on 2026-08-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_payment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='admission_quota',
            field=models.CharField(choices=[('Merit', 'Merit'), ('Management', 'Management'), ('NRI', 'NRI')], default='Merit', max_length=20),
        ),
    ]
