# Generated by Django 5.2.3 on 2026-09-25 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0025_trashedstudent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
    ]
