# Generated by Django 5.2.3 on 2026-08-31 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_photo'),
        ('institutes', '0005_institute_seal_image_institute_signature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accessible_institutes',
            field=models.ManyToManyField(blank=True, related_name='staff_members', to='institutes.institute'),
        ),
        migrations.CreateModel(
            name='UserPrivilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm_admissions_overview', models.BooleanField(default=True, verbose_name='Admissions Overview')),
                ('perm_student_registration', models.BooleanField(default=True, verbose_name='Student Registration')),
                ('perm_student_list', models.BooleanField(default=True, verbose_name='Student List')),
                ('perm_rank_list', models.BooleanField(default=True, verbose_name='Rank List')),
                ('perm_attendance', models.BooleanField(default=True, verbose_name='Attendance Marker')),
                ('perm_notices', models.BooleanField(default=True, verbose_name='News & Notice Board')),
                ('perm_timetables', models.BooleanField(default=True, verbose_name='Class Timetables')),
                ('perm_academic_results', models.BooleanField(default=True, verbose_name='Enter Results')),
                ('perm_course_inventory', models.BooleanField(default=True, verbose_name='Course Inventory')),
                ('perm_fee_reports', models.BooleanField(default=True, verbose_name='Fee Reports & Dues')),
                ('perm_fee_receipts', models.BooleanField(default=True, verbose_name='Fee Receipts')),
                ('perm_payment_details', models.BooleanField(default=True, verbose_name='Payment Details')),
                ('perm_activity_logs', models.BooleanField(default=True, verbose_name='Activity Logs')),
                ('perm_system_backup', models.BooleanField(default=True, verbose_name='System Backup')),
                ('perm_employee_privileges', models.BooleanField(default=True, verbose_name='Employee Privileges')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privileges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
