# Generated by Django 6.0.3 on 2026-03-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institute_logos/'),
        ),
    ]
