# Generated by Django 5.2.3 on 2026-04-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0002_institute_address_institute_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['-id']},
        ),
    ]
