# Generated by Django 5.2.3 on 2026-08-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0004_useractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='seal_image',
            field=models.ImageField(blank=True, help_text='Official seal for documents', null=True, upload_to='institute_seals/'),
        ),
        migrations.AddField(
            model_name='institute',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Signature for official documents like Allotment Memo', null=True, upload_to='institute_signatures/'),
        ),
    ]
