# Generated by Django 6.0.3 on 2026-03-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('textarea', 'Textarea'), ('select', 'Dropdown'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('file', 'File Upload')], max_length=50),
        ),
    ]
