# Generated by Django 6.0.3 on 2026-03-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_formfield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
