# Generated by Django 6.0.3 on 2026-03-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_applicationform_registration_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='is_name_field',
            field=models.BooleanField(default=False, help_text='Check this if this field is Student Name'),
        ),
        migrations.AlterField(
            model_name='fieldoption',
            name='display_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='depends_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
