# Generated by Django 6.0.3 on 2026-03-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_formfield_is_name_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
