# Generated by Django 6.0.3 on 2026-03-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_applicationform_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubject',
            name='include_in_rank',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='is_main_subject',
            field=models.BooleanField(default=False),
        ),
    ]
