# Generated by Django 6.0.3 on 2026-03-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_examsubject_include_in_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='is_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formfield',
            name='is_signature',
            field=models.BooleanField(default=False),
        ),
    ]
