# Generated by Django 6.0.3 on 2026-04-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_formfield_is_photo_formfield_is_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_category_labels',
            field=models.TextField(blank=True, help_text='Enter labels separated by comma (e.g. 1st Sem, 2nd Sem)', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_category_type',
            field=models.CharField(choices=[('semester', 'Semester'), ('year', 'Year')], default='semester', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
