# Generated by Django 6.0.3 on 2026-04-02 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_course_course_category_labels_and_more'),
        ('institutes', '0002_institute_address_institute_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='category_type',
            field=models.CharField(blank=True, choices=[('semester', 'Semester'), ('year', 'Year')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_category_type',
            field=models.CharField(blank=True, choices=[('semester', 'Semester'), ('year', 'Year')], default='semester', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_categories', to='institutes.institute')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='academics.coursecategory'),
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='academics.coursecategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
