# Generated by Django 6.0.3 on 2026-04-02 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_formfield_category_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecategory',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='category_type',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_category_labels',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_category_type',
            field=models.CharField(blank=True, default='semester', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='CourseSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='academics.coursecategory')),
            ],
        ),
        migrations.DeleteModel(
            name='CourseType',
        ),
    ]
