# Generated by Django 5.2.9 on 2026-04-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_remove_coursecategory_institute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubject',
            name='is_sub_subject',
            field=models.BooleanField(default=False),
        ),
    ]
