# Generated by Django 5.2.9 on 2026-04-11 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_examsubject_is_sub_subject'),
        ('applications', '0014_paymentconfig_payment_gateway_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='payment_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='applications.paymentconfig'),
        ),
    ]
