# Generated by Django 5.2.9 on 2026-04-15 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_class_subject'),
        ('institutes', '0002_institute_address_institute_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_forms', to='institutes.academicyear'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='notification_message',
            field=models.TextField(blank=True, help_text='Shown at the top of the student portal', null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='academics.coursecategory'),
        ),
        migrations.AddField(
            model_name='examsubject',
            name='pass_mark',
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name='qualifyingexam',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualifying_exams', to='academics.course'),
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_subjects_v2', to='academics.coursecategory'),
        ),
    ]
