# Generated by Django 5.2.3 on 2026-04-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_applicationform_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['-id']},
        ),
    ]
