# Generated by Django 5.2.3 on 2026-05-02 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_noticeboard_studentdocument_timetable_academicresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. General, Orphan, Ex-Service', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_types', to='academics.applicationform')),
            ],
        ),
    ]
