# Generated by Django 5.2.3 on 2026-05-25 16:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_applicationfeetype'),
        ('applications', '0020_paymentconfig_aggregator_id'),
        ('institutes', '0003_alter_academicyear_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCategoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., General, Sponsorship, Orphan, Fee Waiver', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage discount (0.00 to 100.00)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fee Category Master',
                'verbose_name_plural': 'Fee Category Masters',
            },
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Tuition Fee, Sports Fee, Hostel Fee', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_discountable', models.BooleanField(default=True, help_text='Is this fee type eligible for category/custom discounts?')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fee Type',
                'verbose_name_plural': 'Fee Types',
            },
        ),
        migrations.CreateModel(
            name='ClassYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Year 1, Year 2, Year 3, Semester 1', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_years', to='academics.class')),
            ],
            options={
                'verbose_name': 'Class Year',
                'verbose_name_plural': 'Class Years',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='institutes.academicyear')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.class')),
                ('class_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.classyear')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.course')),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.feecategorymaster')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='institutes.institute')),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structures',
                'unique_together': {('academic_year', 'institute', 'course', 'class_obj', 'class_year', 'fee_category')},
            },
        ),
        migrations.CreateModel(
            name='FeeHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Fine to apply after due date', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heads', to='academics.feestructure')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_heads', to='academics.feetype')),
            ],
            options={
                'verbose_name': 'Fee Head / Structure Item',
                'verbose_name_plural': 'Fee Heads / Structure Items',
            },
        ),
        migrations.CreateModel(
            name='StudentFeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fine_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=50)),
                ('reference_no', models.CharField(blank=True, help_text='Receipt, Transaction ID, etc.', max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='applications.admission')),
                ('fee_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='academics.feehead')),
            ],
            options={
                'verbose_name': 'Student Fee Payment',
                'verbose_name_plural': 'Student Fee Payments',
            },
        ),
    ]
