# Generated by Django 5.2.3 on 2026-08-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_feecategorymaster_feetype_classyear_feestructure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeepayment',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, help_text='Receipt number for fee payment transaction', max_length=50, null=True),
        ),
    ]
