# Generated by Django 5.2.3 on 2026-08-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_studentfeepayment_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeepayment',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='is_cancelled',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
