# Generated by Django 5.2.3 on 2026-08-31 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_studentattendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentdocument',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='doc_type',
            field=models.CharField(blank=True, default='Other', help_text='Category: Student ID Card, Marksheet, TC, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='is_teacher_uploaded',
            field=models.BooleanField(db_index=True, default=False, help_text='True if uploaded by teacher/institute staff'),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_student_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
