# Generated by Django 5.2.3 on 2026-09-25 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0023_feerefundrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRefundRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_items', to='academics.feetype')),
                ('refund_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='academics.feerefundrequest')),
            ],
            options={
                'verbose_name': 'Fee Refund Request Item',
                'verbose_name_plural': 'Fee Refund Request Items',
            },
        ),
    ]
